import { useEffect, useState } from 'react';
import './App.css';
import { BrowserProvider, ethers } from "ethers";
import { Navbar, Footer, Button } from "flowbite-react";
// Import the types generated by the TypeChain library when working with the final version of your contract.
// import { Counter__factory } from './generated/contract-types';

const  App = () => {

  const [getWords, setGetWords] = useState<any>()

  const handleGetWords = async () => {
    console.log('Get contract data')
  }
  
  const handleSetWords = async () => {
  console.log('input get words')
  }

  return (
    <div className=""> <button onClick={handleGetWords}>Get words</button> <input/> <br/>
    <input/> <br/>
    <button onClick={handleSetWords}>Set Words</button> <input onChange={(e)=>{setGetWords(e.target.value)}}/>
    </div>
  );
}

export default App;
